# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - SeguimientoVacantesUV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Instalar PHP y Composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          extensions: mbstring, openssl, pdo, pdo_mysql, pdo_sqlsrv, sqlsrv, tokenizer, xml, ctype, json

      - name: Install PHP dependencies (Production)
        run: composer install --no-dev --optimize-autoloader

      # Instalar Node.js y NPM
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM dependencies
        run: npm install

      - name: Build frontend assets
        run: npm run build

      # Preparar estructura de directorios de Laravel
      - name: Prepare Laravel directories
        run: |
          mkdir -p storage/framework/{cache,sessions,views}
          mkdir -p bootstrap/cache
          chmod -R 775 storage bootstrap/cache

      # Script de inicio para Azure
      - name: Create startup script
        run: |
          echo '#!/bin/bash' > startup.sh
          # 1. Compilación de Activos (Node/NPM)
          echo 'echo "Instalando dependencias de Node.js y compilando para producción..."' >> startup.sh
          echo 'npm install' >> startup.sh
          echo 'npm run build --if-present' >> startup.sh

          # 2. Caché de Configuración y Rutas (Asegura que la APP_KEY se use)
          echo 'echo "Limpiando cachés del framework..."' >> startup.sh
          echo 'php artisan config:clear' >> startup.sh
          echo 'php artisan route:clear' >> startup.sh
          echo 'php artisan view:clear' >> startup.sh

          # 3. Configuración del Document Root de Nginx (Soluciona el 404)
          echo 'echo "Aplicando configuración Nginx para el directorio public..."' >> startup.sh
          echo 'sed -i "s|root /home/site/wwwroot;|root /home/site/wwwroot/public;|g" /etc/nginx/sites-available/default' >> startup.sh
          echo 'sed -i "s|try_files \$uri \$uri/ =404;|try_files \$uri \$uri/ /index.php?\$query_string;|g" /etc/nginx/sites-available/default' >> startup.sh

          # 4. Reiniciar Nginx para aplicar la nueva configuración
          echo 'echo "Reiniciando servicio Nginx..."' >> startup.sh
          echo 'service nginx reload' >> startup.sh

          # 5. Mantener el contenedor activo (Final)
          echo 'echo "Ejecutando proceso principal Nginx..."' >> startup.sh
          echo 'sleep 60d' >> startup.sh

          # Manten el comando del punto de entrada del contenedor original
          echo 'php-fpm' >> startup.sh
          chmod +x startup.sh

      # Configuración específica para Azure
      - name: Add Azure specific configurations
        run: |
          mkdir -p .azure
          echo "WEBSITES_ENABLE_APP_SERVICE_STORAGE=true" > .azure/.env
          echo "SCM_DO_BUILD_DURING_DEPLOYMENT=false" >> .azure/.env

      # Empaquetar para despliegue
      - name: Zip artifact for deployment
        run: |
          chmod -R 755 .
          zip -r release.zip . \
            -x "*.git*" ".github/*" "node_modules/*" "tests/*" "storage/logs/*" ".env*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Extract artifact
        run: unzip release.zip -d .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_30E5EEDFFF694570921F01B2EC773227 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_82AA6698381649D79E69319F96380CFA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8E4EE9E97F4F4FA6B73B3D7E4AF0CA8F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SeguimientoVacantesUV'
          slot-name: 'Production'
          package: release.zip
