# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - SeguimientoVacantesUV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Instalar PHP y Composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          extensions: mbstring, openssl, pdo, pdo_mysql, pdo_sqlsrv, sqlsrv, tokenizer, xml, ctype, json

      - name: Install PHP dependencies (Production)
        run: composer install --no-dev --optimize-autoloader

      # Instalar Node.js y NPM
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM dependencies
        run: npm install

      - name: Build frontend assets
        run: npm run build

      # Preparar estructura de directorios de Laravel
      - name: Prepare Laravel directories
        run: |
          mkdir -p storage/framework/{cache,sessions,views}
          mkdir -p bootstrap/cache
          chmod -R 775 storage bootstrap/cache

      # Script de inicio para Azure
      - name: Create startup script
        run: |
          #!/bin/bash
          # 1. Caché de Configuración y Rutas (Lee variables de Azure, incluyendo APP_KEY)
          echo "Limpiando cachés del framework (para usar variables de Azure)..."
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          # 2. Configuración del Document Root de Nginx (CORRIGE EL 404)
          # Asegúrate de que el archivo existe y es modificable.
          NGINX_CONF="/etc/nginx/sites-available/default"
          echo "Aplicando configuración Nginx para el directorio public..."
          # Reemplazar la carpeta raíz (Document Root)
          sed -i 's|root /home/site/wwwroot;|root /home/site/wwwroot/public;|g' ${NGINX_CONF}
          # Reemplazar el ruteo (para que el framework maneje las rutas)
          sed -i 's|try_files \$uri \$uri/ =404;|try_files \$uri \$uri/ /index.php?\$query_string;|g' ${NGINX_CONF}
          # 3. Reiniciar Nginx para aplicar la nueva configuración
          echo "Reiniciando servicio Nginx..."
          service nginx reload
          # 4. Mantener el contenedor activo (El método más fiable en Azure Linux)
          # Esto arranca Nginx en primer plano y mantiene el contenedor vivo.
          echo "Ejecutando proceso principal Nginx..."
          /usr/sbin/nginx -g 'daemon off;'

      # Configuración específica para Azure
      - name: Add Azure specific configurations
        run: |
          mkdir -p .azure
          echo "WEBSITES_ENABLE_APP_SERVICE_STORAGE=true" > .azure/.env
          echo "SCM_DO_BUILD_DURING_DEPLOYMENT=false" >> .azure/.env

      # Empaquetar para despliegue
      - name: Zip artifact for deployment
        run: |
          chmod -R 755 .
          zip -r release.zip . \
            -x "*.git*" ".github/*" "node_modules/*" "tests/*" "storage/logs/*" ".env*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Extract artifact
        run: unzip release.zip -d .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_30E5EEDFFF694570921F01B2EC773227 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_82AA6698381649D79E69319F96380CFA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8E4EE9E97F4F4FA6B73B3D7E4AF0CA8F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SeguimientoVacantesUV'
          slot-name: 'Production'
          package: release.zip
